#erik sandberg
def sensei_face():
    print '     _     '
    print '   /   \   '
    print '  /     \  '
    print ' | 0  0  | '
    print ' (   &   ) '
    print '  \ --- /  '
    print '   ( | )   '
    print '    (|)    '
    print '     v     '
    print ''
    print ''

def draw_monster(name): # name_of_monster= enemy.name
    if name == 'Blob':
        print '   _______   '
        print '  /       \  '
        print ' ( .\   /. ) '
        print ' (         ) '
        print ' (  (___)  ) '
        print '  (       )  '
        print '   vvvvvvv   '
        print '             '
        peinr '             '
    if name == 'Giant spider':
        print '       /\  /\__wwwwww__/\  /\        '
        print '      /  \/ /          \ \/  \       '
        print '     /    \/   oo  oo   \/    \      '
        print '    /  /\  |            |  /\  \     '
        print '   /  /  \ |  {vvvvvv}  | /  \  \    '
        print '  /  /    \|  {^^^^^^}  |/    \  \   '
        print ' /  /     / \__________/ \     \  \  '
        print '         /                \          '
        print '                                     '
        print '                                     '
    if name == 'Zombie':
        print '   .-^---^-.   '
        print '  /         \  '
        print ' [  x    x   ] '
        print ' [    ..     ] '
        print ' [   _ _ _   ] '
        print '  \ |m|m|m| /  '
        print '    -------    '
        print ''
        print ''
    if name == 'Bat':
        print '    /^\               /^\      '
        print '   /   \    _____    /   \     '
        print '  /     \  /     \  /     \    '
        print ' /   /\  \/ o   o \/  /\   \   '
        print ' \  /  \v/|       |\v/  \  /   '
        print '  \/       \.vwv./       \/    '
        print '                               '
        print ''
        print '' 
    if name == 'Boss':
        print '???'
        print '???'
        print '???'
        print ''
        print ''
